name: docker-image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --pull --no-cache . --tag zasdfgbnm/archlinux-yaourt
    - name: Publish the Docker image
      run: |
        docker login -u zasdfgbnm -p ${{secrets.zasdfgbnm_bot_dockerhub_password}}
        docker push zasdfgbnm/archlinux-yaourt
